site_name: ld3z's Site
site_url: https://ld3z.github.io/site2/
theme:
  name: material
  favicon: images/favicon.png
  font:
    text: Inter
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: green
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: green
      accent: lime

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - git-committers:
      repository: ld3z/site2
      branch: main
  - auto-refresh-build-pages:
      update_message: "This page has been updated. Do you want to reload?"
      yes_button_text: "Yes"
      no_button_text: "No"
      check_interval_seconds: 60
  - minify:
      minify_html: true
  - git-authors
  - glightbox
  - search
  - open-in-new-tab
  - autolinks
  - table-reader

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - sane_lists
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ld3z/
      cards_layout_options:
        font_family: Inter

repo_url: https://github.com/ld3z/site2
repo_name: ld3z/site2

#hooks:
#  - scripts/pf-table.py